# Use root/example as user/password credentials
version: '3.1'

services:

  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_AUTH_SOURCE: admin
    volumes:
      - ./data:/data/db
    ports:
     - "2727:27017"